### ISSUE TITLE
Remove compatibility

### ISSUE THREAD

**Issue by beaufortfrancois** [mhadaily/PWA-Things#1]
`compatibility ` has been removed from the spec.
I think you can omit it below: https://github.com/mhadaily/PWA-Things/blob/b77143320d2029089544134b91bce3602367ec86/src/components/my-webshop-nfc.ts#L195

Source: https://github.com/w3c/web-nfc/commit/3bc03d8ff6b94982f964b06c00cd66185bdf027c

**Comment by mhadaily** [comment]
Thanks, I am sorry I just missed this comment. but I fixed it now.
