### ISSUE TITLE
ignoreRead value is already true

### ISSUE THREAD

**Issue by beaufortfrancois** [mhadaily/PWA-Things#2]
You may want to omit `ignoreRead` as its default value is already `true`

```idl
  boolean ignoreRead = true;
```
https://github.com/mhadaily/PWA-Things/blob/b77143320d2029089544134b91bce3602367ec86/src/components/my-webshop-nfc.ts#L194

**Comment by mhadaily** [comment]
Thanks, and again sorry I missed this. 

fixed!
